// "use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ConvexClientProvider} from "@/app/ConvexClientProvider";
import {Header} from "@/app/header";
import Sidebar from "@/app/sidebar";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ConvexClientProvider>
        <Header/>
        <main className="container mx-auto mt-12">
          <div className="flex gap-8">
            <Sidebar />
            <div className="w-full">
              {children}
            </div>
          </div>
        </main>
      </ConvexClientProvider>
      </body>
    </html>
);
}
